name: Upload to Google Play Store

on:
  push:
    branches:
      - dev

env:
  GOOGLE_PLAY_JSON: ${{ secrets.GOOGLE_PLAY_JSON }}

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/checkout@v2
      with:
        java-version: 11

    - name: Set up Android SDK
      uses: actions/setup-android@v2
      with:
        android-sdk-tools: 29.0.3

    - name: Decode Google Play JSON
      id: decode-google-play-json
      run: echo ${{ env.GOOGLE_PLAY_JSON }} | base64 --decode > ${{ env.HOME }}/google-play.json

    - name: Authenticate with Google Play
      uses: fastlane/action-google-play-authenticate@v1
      with:
        json-key: ${{ env.HOME }}/google-play.json

    - name: Upload to Google Play
      uses: fastlane/action-upload-to-google-play@v2
      with:
        track: internal
        apk-file: app/build/outputs/apk/release/app-release.apk
